# Generated by Django 4.1.7 on 2023-03-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_appointment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pt_height',
            field=models.CharField(choices=[('150', '150'), ('155', '155'), ('160', '160'), ('165', '165'), ('170', '170'), ('175', '175'), ('180', '180'), ('185', '185'), ('190', '190'), ('195', '195'), ('200', '200'), ('205', '205'), ('210', '210'), ('215', '215'), ('220', '220')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='pt_weight',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='addresswithbase',
            name='marrital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='marrital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=20),
        ),
    ]
