# Generated by Django 4.1.7 on 2023-03-24 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_patient_pt_height_patient_pt_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_history', to='clinic.patient'),
        ),
    ]
