# Generated by Django 4.1.7 on 2023-03-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_healthhistory_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='family_history',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='known_disease',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='period',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
